name: Convert to Format

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Convert now
      run: |
       - echo Starting conversion..
       - forfiles /s /m *.langset /c "cmd /c tr \n , < @path | tr -d \r > @path.converted"
